### ISSUE TITLE
[webpack] Uncaught ReferenceError: process is not defined 오류

### ISSUE THREAD

**Issue by baesee0806** [baesee0806/back_office#7]
## 오류 코드

Uncaught ReferenceError: process is not defined
    at ./src/apis/firebaseService.js (firebaseService.js:6:11)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/page/SignIn.jsx (Messenger.jsx:7:25)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/App.jsx (index.js:176:1)
    at __webpack_require__ (bootstrap:24:1)
    at startup:6:1
    at startup:6:1

**Comment by baesee0806** [comment]
## 해결 과정
Webpack v5부터 node.js polyfill이 자동적으로 적용되는 기능이 제거된 것이 원인이라고 한다.(overflow검색결과)
모듈을 추가해야한다고 한다 
```
yarn add -D process
```

### webpack.config.js 추가

module.exports = {
  ...
  plugins: [
      new webpack.ProvidePlugin({
             process: 'process/browser.js',
      }),
  ],
}
